jobs:
  - name: qa
    serial_groups: [qa-applies]
    max_in_flight: 1
    plan:
      - get: dw-al2-ecs-ami
      - get: dataworks-aws-ingestion-ecs-cluster
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'qa'
