jobs:
  - name: update-pipeline
    plan:
      - get: dataworks-aws-ingestion-ecs-cluster
        resource: dataworks-aws-ingestion-ecs-cluster-update-pipeline
        trigger: true
      - task: aviator
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((dataworks.docker_aviator_repository))
              version: ((dataworks.docker_aviator_version))
          run:
            path: sh
            args:
              - -exc
              - |
                sed -i 's/fly/nofly/' aviator.yml
                /usr/bin/aviator -f aviator.yml
                mv aviator_pipeline.yml ../pipeline
            dir: dataworks-aws-ingestion-ecs-cluster
          inputs:
            - name: dataworks-aws-ingestion-ecs-cluster
          outputs:
            - name: pipeline
      - set_pipeline: ingestion-ecs-cluster
        file: pipeline/aviator_pipeline.yml
